export function DemoMermaidDiagram() {
  return (
    <div className="my-4 p-4 bg-[#0F1115] border border-white/5 rounded-lg overflow-hidden">
      <svg viewBox="0 0 600 280" className="w-full h-auto font-sans" style={{ fontFamily: 'Inter, sans-serif' }}>
        {/* Definitions */}
        <defs>
          <marker id="arrowhead" markerWidth="10" markerHeight="7" refX="9" refY="3.5" orient="auto">
            <polygon points="0 0, 10 3.5, 0 7" fill="#64748b" />
          </marker>
        </defs>

        {/* Node 1: Hyperkaliämie */}
        <g transform="translate(220, 20)">
           <rect x="0" y="0" width="160" height="40" rx="6" fill="#4c1d95" stroke="#a855f7" strokeWidth="2" fillOpacity="0.2" />
           <text x="80" y="25" textAnchor="middle" fill="#e9d5ff" fontSize="12" fontWeight="bold">Hyperkaliämie (&gt; 5.5)</text>
        </g>

        {/* Arrow 1 */}
        <line x1="300" y1="60" x2="300" y2="90" stroke="#64748b" strokeWidth="1.5" markerEnd="url(#arrowhead)" />

        {/* Node 2: Membranpotential */}
        <g transform="translate(200, 90)">
           <rect x="0" y="0" width="200" height="40" rx="6" fill="#1e293b" stroke="#334155" strokeWidth="1" />
           <text x="100" y="25" textAnchor="middle" fill="#cbd5e1" fontSize="11">Ruhepotential weniger negativ</text>
        </g>

        {/* Arrow Split */}
        <line x1="300" y1="130" x2="300" y2="150" stroke="#64748b" strokeWidth="1.5" />
        <line x1="300" y1="150" x2="150" y2="150" stroke="#64748b" strokeWidth="1.5" />
        <line x1="300" y1="150" x2="450" y2="150" stroke="#64748b" strokeWidth="1.5" />
        <line x1="150" y1="150" x2="150" y2="170" stroke="#64748b" strokeWidth="1.5" markerEnd="url(#arrowhead)" />
        <line x1="450" y1="150" x2="450" y2="170" stroke="#64748b" strokeWidth="1.5" markerEnd="url(#arrowhead)" />

        {/* Node 3: Repolarisation (Links) */}
        <g transform="translate(50, 170)">
           <rect x="0" y="0" width="200" height="40" rx="6" fill="#134e4a" stroke="#14b8a6" strokeWidth="1" fillOpacity="0.2" />
           <text x="100" y="25" textAnchor="middle" fill="#99f6e4" fontSize="11">Schnellere Repolarisation</text>
        </g>

         {/* Node 4: Depolarisation (Rechts) */}
        <g transform="translate(350, 170)">
           <rect x="0" y="0" width="200" height="40" rx="6" fill="#450a0a" stroke="#ef4444" strokeWidth="1" fillOpacity="0.2" />
           <text x="100" y="25" textAnchor="middle" fill="#fca5a5" fontSize="11">Na+ Kanal Inaktivierung</text>
        </g>

        {/* Arrow Final */}
        <line x1="150" y1="210" x2="150" y2="230" stroke="#64748b" strokeWidth="1.5" markerEnd="url(#arrowhead)" />
        <line x1="450" y1="210" x2="450" y2="230" stroke="#64748b" strokeWidth="1.5" markerEnd="url(#arrowhead)" />

        {/* Result 1 */}
        <g transform="translate(70, 230)">
           <rect x="0" y="0" width="160" height="30" rx="15" fill="#14b8a6" fillOpacity="0.1" stroke="none" />
           <text x="80" y="20" textAnchor="middle" fill="#2dd4bf" fontSize="12" fontWeight="bold">Zelt-T Welle</text>
        </g>

        {/* Result 2 */}
        <g transform="translate(370, 230)">
           <rect x="0" y="0" width="160" height="30" rx="15" fill="#ef4444" fillOpacity="0.1" stroke="none" />
           <text x="80" y="20" textAnchor="middle" fill="#f87171" fontSize="12" fontWeight="bold">QRS-Verbreiterung</text>
        </g>

      </svg>
      <div className="flex justify-between px-2 mt-2">
         <span className="text-[9px] text-neutral-500 font-mono">FLOWCHART: PATHOPHYSIOLOGY</span>
         <span className="text-[9px] text-neutral-600 font-mono">GENERATED BY MERMAID</span>
      </div>
    </div>
  );
}
